schema:
  - "../../orchestration/src/typeDefs/*.graphql"
extensions:
  graphql-info:
    targetDir: ./docs
    overrides:
      types:
        query: '../document/src'
        mutation: '../document/src'
      navigation: '../nav-search/src/'